name: Build and Test Docker Image for Radicale
on:
  push:

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    env:
      AUTH_PLUGIN: startmail
      STORAGE_PLUGIN: startmail
      WEB_PLUGIN: none
    steps:
      - uses: actions/checkout@v2
      - name: Update Configuration
        run: |
          envsubst < radicale.cfg > radicale-out.cfg
          mv radicale-out.cfg radicale.cfg
      - name: Build Docker Image
        run: docker build --tag radicale .
      - name: Create Radicale Data Folder
        run: mkdir data
      - name: Run Docker Image
        run: docker run -d -p 5232:5232 --name=radicale -v data:/var/lib/radicale radicale
      - name: Test Docker Image
        run: sleep 5 && curl -vL localhost:5232 | grep "Radicale works"
      - name: Remove Docker Images
        run: docker rm -f radicale
